import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header"
import headerStyles from "./header.module.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Header className={headerStyles.header}></Header> */}
      <body className={inter.className}>{children}</body>
      <header className="bg-cyan-500 text-center"> African Diety : Goddess Yemaya</header>

    </html>
  );
}
